// Remotion Root Component
import React from 'react';
import { Composition, registerRoot } from 'remotion';
import { TextScene } from './compositions/TextScene';
import { ImageScene } from './compositions/ImageScene';
import { MultiSceneVideo } from './compositions/MultiSceneVideo';

export const RemotionRoot = () => {
  return (
    <>
      <Composition
        id="TextScene"
        component={TextScene}
        durationInFrames={150}
        fps={30}
        width={1920}
        height={1080}
        defaultProps={{
          text: 'Hello from Enhanced MAKER',
          backgroundColor: '#000000',
          textColor: '#FFFFFF',
        }}
      />
      
      <Composition
        id="ImageScene"
        component={ImageScene}
        durationInFrames={180}
        fps={30}
        width={1920}
        height={1080}
        defaultProps={{
          imageUrl: 'https://picsum.photos/1920/1080',
          overlayText: 'Generated by Remotion',
        }}
      />
      
      <Composition
        id="MultiSceneVideo"
        component={MultiSceneVideo}
        durationInFrames={300}
        fps={30}
        width={1920}
        height={1080}
        defaultProps={{
          scenes: [
            { type: 'text', content: 'Scene 1', duration: 90 },
            { type: 'text', content: 'Scene 2', duration: 90 },
            { type: 'text', content: 'Scene 3', duration: 120 },
          ],
        }}
        calculateMetadata={({ props }) => {
          // Calculate total duration from all scenes
          const totalDuration = props.scenes?.reduce((sum, scene) => sum + (scene.duration || 90), 0) || 300;
          return {
            durationInFrames: totalDuration,
            fps: 30,
            width: 1920,
            height: 1080,
          };
        }}
      />
    </>
  );
};

// Register the root component
registerRoot(RemotionRoot);
